### ISSUE TITLE
Animation des cartes quand on les retourne.

### ISSUE THREAD

**Issue by bidetaggle** [podzit/CovidGame#12]
Voilà un flow possible que je vois pour animer les cartes:

1. Les cartes sont face cachées
2. L'utilisateur clique sur `jouer`
3. Les données de chaque carte sont générées.
4. Les cartes se retournent dans une animation fluide ([Voir cet exemple en CSS](https://www.w3schools.com/howto/howto_css_flip_card.asp))
5. L'utilisateur click sur `rejouer`
6. Les deux cartes retournées disparaissent avec un effet de swipe sur le côté laissant apparaître de nouvelles cartes face cachées en dessous
7. Retour à 1.

Qu'est-ce que t'en penses?

**Comment by podzit** [comment]
Est-ce qu'il ne serait pas plus fluide qu'après l'étape 5:
6- les deux cartes swipe sur des faces cachées
7- les deux cartes flip sur la face visible
Sans intervention du joueur? sinon ça fait 2 clics coup sur coup "rejouer" + "jouer" j'ai peur que ce soit usant.

**Comment by bidetaggle** [comment]
Je suis pas sûr de bien comprendre ton étape 6. Tu veux dire, les cartes se re-retourne face cachées?

Effectivement ça fait cliquer 2 fois, c'est peut-être mieux un seul click, voilà comment on peut faire la boucle de jeu:

1. L'utilisateur clique sur rejouer
2. Les cartes face visible glissent sur le côté et disparaissent, laissant apparaître les cartes face cachées en dessous.
3. Les données de chaque nouvelle carte sont générées.
4. Les cartes se retournent (animation).
5. Retour à 1.

Et simplement lorsque c'est la première fois que l'on click sur jouer on passe directement de l'étape 1 à 3 sans passer par 2.

Qu'est-ce que t'en penses?

**Comment by podzit** [comment]
Oui c'est exactement ce que je voulais dire. Désolé si ce n'était pas clair.

**Comment by bidetaggle** [comment]
Pas de problème :)

**Comment by podzit** [comment]
J'ai pushé un début d'effet de retournement. Dis moi ce que t'en pense.

**Comment by podzit** [comment]
Vu que j'étais bien parti, j'ai ajouté une "poche" à 50$, transformé le bouton "jouer" en mises de 1,2,5 et 10$ et j'ai donné une orientation "jeu de casino" à covidgame.

En gros:
- on mise 
- si on gagne on remporte carteToi.force*mise
- si match nul on perd la mise
- si on perd c'est carteEnnemi.force*mise

à 0$ dans "ta poche" un popup "game over" s'affiche.

**Comment by podzit** [comment]
Je me suis enflammé, j'ai ajouté une page de classement des meilleurs scores et tout le fonctionnement qui va avec en php.
Le tout sans base de donnée, juste avec un fichier csv.
Fonctionnement:
Durant le jeu chaque fois que `$poche` atteint un nouveau score, ça passe dans la variable `$hiscore`.
Lorsque la poche arrive à 0 ou moins, le joueur a la possibilité de mettre un pseudo.
Le pseudo et le score sont transmis à `scores.php` qui écrit dans le fichier `assets/scores.csv`, puis reli le fichier et les 10 meilleurs scores sont mis en forme dans la page `scores.php`.

**Comment by podzit** [comment]
Le retournement des cartes et les différents `settimeout` produisent l'effet voulu.
